name: fact2023
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11.5
  - pip=23.3.1
  - pytorch-cuda=11.8
  - pytorch=2.1.0
  - torchvision=0.16.0
  - torchaudio=2.1.0
  - pip:
    - kmedoids
    - gdown
    - python-mnist
    - pulp
    - scikit-learn
    - zoopt
    - pyckmeans
    - torch
    - pandas
    - seaborn